# debug:
# 	g++ finite-elements.cpp -o finite-elements.out -Wall -D_GLIBCXX_DEBUG -g && ./finite-elements.out
# release:
# 	g++ finite-elements.cpp -o finite-elements.out -Wall -O3 && ./finite-elements.out

debug:
	g++ finite-elements-heatsink.cpp -o finite-elements-heatsink.out -lboost_filesystem -Wall -D_GLIBCXX_DEBUG -g && ./finite-elements-heatsink.out
release:
	g++ finite-elements-heatsink.cpp -o finite-elements-heatsink.out -lboost_filesystem -Wall -O3 && ./finite-elements-heatsink.out
