# debug:
# 	g++ finite-elements.cpp -o finite-elements -Wall -D_GLIBCXX_DEBUG -g && ./finite-elements
# release:
# 	g++ finite-elements.cpp -o finite-elements -Wall -O3 && ./finite-elements

debug:
	g++ finite-elements-heatsink.cpp -o finite-elements-heatsink -Wall -D_GLIBCXX_DEBUG -g && ./finite-elements-heatsink
release:
	g++ finite-elements-heatsink.cpp -o finite-elements-heatsink -Wall -O3 && ./finite-elements-heatsink
